on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  universal:
    name: "Build all-apple-darwin"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Build binary
        shell: bash
        run: |
          mkdir -p target/all-apple-darwin/release
          cd artifacts
          unzip -q helloworld-${{ inputs.version }}-x86_64-apple-darwin.zip
          unzip -q helloworld-${{ inputs.version }}-aarch64-apple-darwin.zip
          lipo -create helloworld-${{ inputs.version }}-x86_64-apple-darwin/bin/helloworld \
            helloworld-${{ inputs.version }}-aarch64-apple-darwin/bin/helloworld \
            -output ../target/all-apple-darwin/release/helloworld

      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PLATFORM_OVERRIDE: osx

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: artifacts
          path: |
            out/jreleaser/assemble/helloworld/archive/*.zip

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: jreleaser-all-apple-darwin
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
